apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: flaskapp12.azurecr.io/flask:0.0.3   # <-- immagine dal tuo ACR
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      # Importante: AKS userà la Managed Identity con ruolo AcrPull per scaricare l’immagine
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer  # espone l’app con IP pubblico
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000        # porta pubblica
      targetPort: 5000 # porta interna del container Flask
